### PR TITLE
Review e subdiagrams for "chatting with the cat"

### PR DESCRIPTION
**Pull request by sambarza**
Review of:
- chatting-with-the-cat
- recall-set-relevant-memory

New diagrams for:
- call-the-cat
- set-agent-input
- execute-agent
- return-answer

Yet to set the links to the documentation

### CODE REVIEW

**Comment by nicola-corbellini** [comment]
great, thank you!

Sorry, I don't want to sound too picky. I've seen you use "user prompt", "user message" and "user input". If you agree, we could stick with only one naming for consistency.
For instance, I would go either with "input" or "message" to differentiate it from the "prompt", that is the whole message consisting of the user's input and the other info.

**Comment by sambarza** [comment]
You are not too picky, any suggestion is appreciated!

I agree, confusion, and "user prompt" is not the correct term to use.

I'm reading the source code and I try to recap the flow:
- the method `__call__` receive `user_message_json`, in this dictionary there are `text`, `user_id` (if any) and `prompt_settings`
- `user_message_json` is saved as-is in the `working_memory`
- in the `agent_input` dictionary, there is the key `input` that contains only `working_memory[text]`

So, I can use the term "user message" for the step 1:
image
and in working memory:
image

In the `agent input` , should we use `user text` or should we keep it simple and use `user message` here as well? (not exactly correct)
I vote for `user text` and show how is that filled in details in the diagram step 5 "set agent input"

(so far, I have ignored `prompt settings`, I will update the diagrams in a later time)

**Comment by nicola-corbellini** [comment]
Sorry maybe I misunderstood the diagram then.
In my mind, what you called `user prompt` was the text that the user writes in the chat. Namely, `user_message_json["text"]`.
If you refer to the whole JSON sent via websocket , maybe we can call it another way, e.g. `websocket message` or something else. Hence, we explain the user that `websocket message` consists in `user message`, `user id` and so on (similar to what you did with `agent input`).

Then, as you said, from the working memory, we are retrieving only the `text` key. I.e., `working_memory["user_message_json"]["text"]`. This is, indeed, the same text as before, so I would call it the same (e.g. `user message`). Then, I think its correct and comprehensible as you did, i.e. you showed that the `agent input` consists in `user message`, `episodic memory` and so on.

Does this make sense to you?

**Comment by sambarza** [comment]
Pushed now a the pull request #15.
I think we can continue there on the new PR.

**Pull request merged**
