### PR TITLE
Use of plugin drawio, fix hooks button and missing hooks notes

### PR DESCRIPTION
**Pull request by sambarza**
- use of plugin drawio:

  The standard plugin (for embeed drawio files) don't hide the EDIT button, fixed changing the SUB_TEMPLATE constant.

  Locally, the fix in the plugin to hide the EDIT button works, but on GitHub, the action would have installed the public 
  version of the plugin without our fix, and the EDIT button would have been visible.

  I will send a pull request to the upstream project of the plugin. For now, as a workaround, I have transformed the plugin 
  into a hook.

- Fix hooks button 
- Add missing hooks notes

### CODE REVIEW

**Comment by sambarza** [comment]
I kept these two steps visible even when the hooks are hidden; otherwise, the numbering of the steps would have had gaps:
image

**Comment by sambarza** [comment]
New feature request to the plugin project:
onixpro/mkdocs-drawio-file#11

**Comment by pieroit** [comment]
Nice!!!

**Comment by nicola-corbellini** [comment]
Awesome thanks!

**Pull request merged**
