### PR TITLE
Plugin guide without template, new menu Using the Plugin Template

### PR DESCRIPTION
**Pull request by sambarza**
Refers to #31 

- "Preparing a Plugin" explain the creation of empty plugin from scratch without using template
- New menu "Plugins Registry->Using the Plugin Template" with explanation on using plugin template

### CODE REVIEW

**Review by nicola-corbellini — APPROVED** [review]

**Comment by nicola-corbellini** [comment]
Sorry for the delay, forgot about this

**Comment by EugenioPetulla** [comment]
Sorry, didn't see this one.

I'm going to review it in 5 minutes.

Thank you 🫂

**Review by EugenioPetulla — APPROVED** [review]

**Comment by EugenioPetulla** [comment]
I merged it. ATM is good!

As soon as the new version with the new stable hooks is released we want to add also an example of settings implementation. 

@nicola-corbellini @sambarza Do we want to open an issue in order to remember to update this one?

**Comment by nicola-corbellini** [comment]
There is [this one](https://cheshire-cat-ai.github.io/docs/technical/plugins/settings/) already.
Would you add another one?

**Comment by EugenioPetulla** [comment]
mmmm maybe no... but we can mention it in the "write your first tool" section.

Something like "you can let your user set this parameter if you need by implementing settings. Follow this link and read the doc!"

**Comment by nicola-corbellini** [comment]
Yep, agree. Also, internal links inside the doc are missing. They could be useful.

**Comment by sambarza** [comment]
> mmmm maybe no... but we can mention it in the "write your first tool" section.
> 
> Something like "you can let your user set this parameter if you need by implementing settings. Follow this link and read the doc!"

Agree, the settings concept is missing.
Instead of a link, we can update the quickstart section inserting settings in the "write the tool" step, source code example and how to use in admin portal

**Comment by sambarza** [comment]
> Yep, agree. Also, internal links inside the doc are missing. They could be useful.

The internal links are intentionally missing in the quickstart section, to "suggest" a "linear" learning path, however maybe you are correct, a section at the bottom with "Reference Links" can be usefull

**Comment by sambarza** [comment]
Like this:

image

**Pull request merged**
